### ISSUE TITLE
Stop counting up after time up

### ISSUE THREAD

**Issue by jaysonknz** [fraggerfox/countdown-timer#1]
Hi there, is it possible to remove some code from the JS to stop the timer counting up after the time has finished? Many thanks in advance!

**Comment by fraggerfox** [comment]
Hello jaysonknz

I have not looked into the code for quite sometime now.

Would an option / checkbox to stop it from counting up also suffice?

**Comment by jaysonknz** [comment]
Hi there,

Thanks for your fast reply. Yes that would definitely also suffice.

Many thanks


On 3/11/2018, at 7:22 PM, Santhosh Raju <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello jaysonknz

I have not looked into the code for quite sometime now.

Would an option / checkbox to stop it from counting up also suffice?

**Comment by fraggerfox** [comment]
I have added a new branch called "allow-overtime-checkbox" which has a checkbox (if unchecked) that helps stop the timer once it hits zero.

The checkbox could use a bit of CSS so that the theme matches the rest of the UI, but I am not proficient enough to make this change accurately.

Let me know how this works out for you.

**Comment by fraggerfox** [comment]
I thought of merging the changes with the master branch, but then on second thoughts I did not want to change the simplistic look of the original timer. So I shall maintain this in a branch of it's own. And update documentation to match with the changes.

You can access it [here](https://github.com/fraggerfox/countdown-timer/tree/allow-overtime-checkbox).

Marking this issue as closed.
