### ISSUE TITLE
Brilliant!  Document easier way to run it.

### ISSUE THREAD

**Issue by gwhammett** [fraggerfox/countdown-timer#2]
This TED-like talk timer is brilliant!  One suggestion: In the readme.md file at https://github.com/fraggerfox/countdown-timer, where it says "You will need to put the files in a Web Server (like Apache for example) and then access the index.html which will load the Countdown Timer UI", you can add:

"or download these files to your computer and access the index.html file locally on your computer."

This avoids the need to find or know about an Apache server.

**Comment by fraggerfox** [comment]
The reason I did not write about accessing index.html locally was because of the fact that when I tried it out and sometimes the Javascript was not working as expected. But this was quite sometime back.

Does it work as expected when you load it up locally via index.html?

**Comment by gwhammett** [comment]
It works fine for me on my local computer (a Macbook).

**Comment by fraggerfox** [comment]
Alright, I shall update README.md and then close this ticket.

Thank you for testing out and confirming it works.

**Comment by gwhammett** [comment]
Congrats again on a very nice talk timer.  Have you put it on a web server 
somewhere?  It might get lots of use.  A lot of people have no idea what 
to do with github, but they know how to go to a web server.  If it is on 
a web server somehwere, you might put a link in your github reademe.md 
file.

**Comment by fraggerfox** [comment]
Well most of the timer is nothing but the trimmed down version of the TED timer, with some minor modifications sprinkled in :).

I have not put it on a web server, mostly because I do not have a place to host it at the moment. But if I do manage to host it somewhere, I shall update the README.md with the appropriate link.

Meanwhile I have updated the document to include the alternative way to open up the timer based on your suggestion. It should be fixed in this commit fraggerfox/countdown-timer@74432ece3

Once again thank you for testing and reporting back!

**Comment by gwhammett** [comment]
Dear Santhosh,

I put your countdown timer online at

http://www.princeton.edu/~hammett/TED-like_talk_timer/

If you prefer a different link name, I can change it.

   -Greg

**Comment by fraggerfox** [comment]
Thank you Greg!! That is very kind of you.

I have updated the README.md with a reference to this link.
