### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by saschafoerster** [fraggerfox/countdown-timer#3]
It would be great if there was a way to remote control the timer, so the speaker can see it, but no one has to touch or change the screen in front of the audience. #FeatureRequest

**Comment by fraggerfox** [comment]
Hello @saschafoerster 

I am not sure how this can be implemented. Since I have quite limited skills with HTML + JavaScript.

That being said, one can have VNC installed in the machine running the timer and change stuff. This was actually done for one of the places where this timer was used.

Do you think this would suffice as a solution for remote controlling the timer without anyone touching or changing the screen in  front of the audience?

Also this keeps intact the simplicity of the timer design.

Regards
Santhosh

**Comment by captn3m0** [comment]
Since there is no backend server here, an easy way to set this would be via Firebase.

The flow would be something like:

1. Frontend Loads, creates a channel with firebase.
2. Frontend JS saves the channel ID against a 8 digit passcode
3. You open `/remote.html` on your phone which gives you the same configuration options.
4. The passcode you type in remote.html is used to push configuration to the firebase channel.

But yeah - this might be a lot of work when simple VNC setup will suffice.

**Comment by captn3m0** [comment]
Or if you wanna stay away from hosted services, might be possible with webrtc ?

**Comment by saschafoerster** [comment]
Anyway, with Remote or without. It looks gorgeous and I'm really in love with it! :) Thanks! 
An idea: you could create an individual remote-timer-id like https://countdown.ted.com/[secretcode], and wherever I start the play button, all the timers with the same url start around the same time. Would this be possible? Maybe it is just a file, that is created, as soon it is there, the timer starts?

**Comment by fraggerfox** [comment]
@saschafoerster , not sure since this may require some sort of server side code to deal with the "secretcode" and this timer does not have that. 

I think the approach which @captn3m0 suggested makes sense if you would like to have a method to control the timer remotely, if using VNC is not an option.

What do you think?

**Comment by saschafoerster** [comment]
Instead of firebase I would just use a simple file with text or sqlite. But the rest sounds nice!

**Comment by fraggerfox** [comment]
@saschafoerster May I close this ticket if this has been resolved?

**Comment by saschafoerster** [comment]
I also tried some remote control tools like https://airdroid.com/de/ on an Android-Device. So it is okay for me now, if this feature isn't build into the countdown-timer itself.

**Comment by fraggerfox** [comment]
Cool, thanks for notifying the solution you came across.
